export interface HelminthRegistryEntry {
  slug: string;
  name: string;
  armory_key: string;
  de_paths: readonly string[];
}

export const HELMINTH_REGISTRY_ENTRIES: readonly HelminthRegistryEntry[] = [
  {
    slug: 'Airburst',
    name: 'Airburst',
    armory_key: '/Armory/Helminth/Airburst',
    de_paths: ['/Lotus/Powersuits/Tengu/Abilities/TenguBurstAbility'],
  },
  {
    slug: 'Aquablades',
    name: 'Aquablades',
    armory_key: '/Armory/Helminth/Aquablades',
    de_paths: ['/Lotus/Powersuits/Yareli/Abilities/YareliDisksAbility'],
  },
  {
    slug: 'Banish',
    name: 'Banish',
    armory_key: '/Armory/Helminth/Banish',
    de_paths: ['/Lotus/Powersuits/Magician/Abilities/BanishAbility'],
  },
  {
    slug: 'BloodAltar',
    name: 'Blood Altar',
    armory_key: '/Armory/Helminth/BloodAltar',
    de_paths: ['/Lotus/Powersuits/Garuda/Abilities/GarudaSiphonAbility'],
  },
  {
    slug: 'BreachSurge',
    name: 'Breach Surge',
    armory_key: '/Armory/Helminth/BreachSurge',
    de_paths: ['/Lotus/Powersuits/Wisp/Abilities/WispHarnessAbility'],
  },
  {
    slug: 'Brightbonnet',
    name: 'Brightbonnet',
    armory_key: '/Armory/Helminth/Brightbonnet',
    de_paths: ['/Lotus/Powersuits/Nokko/Abilities/NokkoPowerShroomAbility'],
  },
  {
    slug: 'ChyrinkaPillar',
    name: 'Chyrinka Pillar',
    armory_key: '/Armory/Helminth/ChyrinkaPillar',
    de_paths: ['/Lotus/Powersuits/ConcreteFrame/Abilities/ConcretePillarAbility'],
  },
  {
    slug: 'CoilHorizon',
    name: 'Coil Horizon',
    armory_key: '/Armory/Helminth/CoilHorizon',
    de_paths: ['/Lotus/Powersuits/Gyre/Abilities/GyreSphereAbility'],
  },
  {
    slug: 'Condemn',
    name: 'Condemn',
    armory_key: '/Armory/Helminth/Condemn',
    de_paths: ['/Lotus/Powersuits/Priest/Abilities/PriestCondemnAbility'],
  },
  {
    slug: 'DarkVerse',
    name: 'Dark Verse',
    armory_key: '/Armory/Helminth/DarkVerse',
    de_paths: ['/Lotus/Powersuits/Pagemaster/Abilities/PagemasterDeathAbility'],
  },
  {
    slug: 'Decoy',
    name: 'Decoy',
    armory_key: '/Armory/Helminth/Decoy',
    de_paths: ['/Lotus/Powersuits/Loki/Abilities/DecoyAbility'],
  },
  {
    slug: 'Defy',
    name: 'Defy',
    armory_key: '/Armory/Helminth/Defy',
    de_paths: ['/Lotus/Powersuits/MonkeyKing/Abilities/MonkeyDeathNewAbility'],
  },
  {
    slug: 'Desiccation',
    name: 'Desiccation',
    armory_key: '/Armory/Helminth/Desiccation',
    de_paths: ['/Lotus/Powersuits/Sandman/Abilities/SandmanBlastAbility'],
  },
  {
    slug: 'Dispensary',
    name: 'Dispensary',
    armory_key: '/Armory/Helminth/Dispensary',
    de_paths: ['/Lotus/Powersuits/Odalisk/Abilities/OdaliskDispensaryAbility'],
  },
  {
    slug: 'Eclipse',
    name: 'Eclipse',
    armory_key: '/Armory/Helminth/Eclipse',
    de_paths: ['/Lotus/Powersuits/Harlequin/Abilities/LightAbility'],
  },
  {
    slug: 'ElementalWard',
    name: 'Elemental Ward',
    armory_key: '/Armory/Helminth/ElementalWard',
    de_paths: ['/Lotus/Powersuits/Dragon/Abilities/DragonLuckAbility'],
  },
  {
    slug: 'Empower',
    name: 'Empower',
    armory_key: '/Armory/Helminth/Empower',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthStrengthAbility'],
  },
  {
    slug: 'EnergizedMunitions',
    name: 'Energized Munitions',
    armory_key: '/Armory/Helminth/EnergizedMunitions',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthEfficiencyAbility'],
  },
  {
    slug: 'Ensnare',
    name: 'Ensnare',
    armory_key: '/Armory/Helminth/Ensnare',
    de_paths: ['/Lotus/Powersuits/Khora/Abilities/KhoraTwirlAbility'],
  },
  {
    slug: 'Evade',
    name: 'Evade',
    armory_key: '/Armory/Helminth/Evade',
    de_paths: ['/Lotus/Powersuits/Frumentarius/Abilities/FrumentariusCloakAbility'],
  },
  {
    slug: 'ExpediteSuffering',
    name: 'Expedite Suffering',
    armory_key: '/Armory/Helminth/ExpediteSuffering',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthStatusAbility'],
  },
  {
    slug: 'FireBlast',
    name: 'Fire Blast',
    armory_key: '/Armory/Helminth/FireBlast',
    de_paths: ['/Lotus/Powersuits/Ember/Abilities/FireBlastAbility'],
  },
  {
    slug: 'FireWalker',
    name: 'Fire Walker',
    armory_key: '/Armory/Helminth/FireWalker',
    de_paths: ['/Lotus/Powersuits/Nezha/Abilities/NezhaTrailAbility'],
  },
  {
    slug: 'FracturedBlast',
    name: 'Fractured Blast',
    armory_key: '/Armory/Helminth/FracturedBlast',
    de_paths: ['/Lotus/Powersuits/Geode/Abilities/GeodeShardsAbility'],
  },
  {
    slug: 'Gloom',
    name: 'Gloom',
    armory_key: '/Armory/Helminth/Gloom',
    de_paths: ['/Lotus/Powersuits/Wraith/Abilities/WraithGloomAbility'],
  },
  {
    slug: 'GoldenInstinct',
    name: 'Golden Instinct',
    armory_key: '/Armory/Helminth/GoldenInstinct',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthTreasureAbility'],
  },
  {
    slug: 'HideousResistance',
    name: 'Hideous Resistance',
    armory_key: '/Armory/Helminth/HideousResistance',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthProcBlockAbility'],
  },
  {
    slug: 'IceWave',
    name: 'Ice Wave',
    armory_key: '/Armory/Helminth/IceWave',
    de_paths: ['/Lotus/Powersuits/Frost/Abilities/IceSpikeAbility'],
  },
  {
    slug: 'InfestedMobility',
    name: 'Infested Mobility',
    armory_key: '/Armory/Helminth/InfestedMobility',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthSpeedAbility'],
  },
  {
    slug: 'Larva',
    name: 'Larva',
    armory_key: '/Armory/Helminth/Larva',
    de_paths: ['/Lotus/Powersuits/Infestation/Abilities/InfestTendrilsAbility'],
  },
  {
    slug: 'Lull',
    name: 'Lull',
    armory_key: '/Armory/Helminth/Lull',
    de_paths: ['/Lotus/Powersuits/Pacifist/Abilities/PacifistWaveAbility'],
  },
  {
    slug: 'LycathsHunt',
    name: "Lycath's Hunt",
    armory_key: '/Armory/Helminth/LycathsHunt',
    de_paths: ['/Lotus/Powersuits/Werewolf/Abilities/WerewolfLeapAbility'],
  },
  {
    slug: 'MarkedForDeath',
    name: 'Marked for Death',
    armory_key: '/Armory/Helminth/MarkedForDeath',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthStunAbility'],
  },
  {
    slug: 'MastersSummons',
    name: "Master's Summons",
    armory_key: '/Armory/Helminth/MastersSummons',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthCompanionAbility'],
  },
  {
    slug: 'MindControl',
    name: 'Mind Control',
    armory_key: '/Armory/Helminth/MindControl',
    de_paths: ['/Lotus/Powersuits/Jade/Abilities/MindControlAbility'],
  },
  {
    slug: 'Molt',
    name: 'Molt',
    armory_key: '/Armory/Helminth/Molt',
    de_paths: ['/Lotus/Powersuits/Saryn/Abilities/ShedAbility'],
  },
  {
    slug: 'Nourish',
    name: 'Nourish',
    armory_key: '/Armory/Helminth/Nourish',
    de_paths: ['/Lotus/Powersuits/Devourer/Abilities/DevourerConsumeAbility'],
  },
  {
    slug: 'NullStar',
    name: 'Null Star',
    armory_key: '/Armory/Helminth/NullStar',
    de_paths: ['/Lotus/Powersuits/AntiMatter/Abilities/NullStarAbility'],
  },
  {
    slug: 'Omamori',
    name: 'Omamori',
    armory_key: '/Armory/Helminth/Omamori',
    de_paths: ['/Lotus/Powersuits/Koumei/Abilities/KoumeiBlockAbility'],
  },
  {
    slug: 'OphanimEyes',
    name: 'Ophanim Eyes',
    armory_key: '/Armory/Helminth/OphanimEyes',
    de_paths: ['/Lotus/Powersuits/Choir/Abilities/ChoirEyesAbility'],
  },
  {
    slug: 'ParasiticArmor',
    name: 'Parasitic Armor',
    armory_key: '/Armory/Helminth/ParasiticArmor',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthShieldArmorAbility'],
  },
  {
    slug: 'Perspicacity',
    name: 'Perspicacity',
    armory_key: '/Armory/Helminth/Perspicacity',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthHackAbility'],
  },
  {
    slug: 'Petrify',
    name: 'Petrify',
    armory_key: '/Armory/Helminth/Petrify',
    de_paths: ['/Lotus/Powersuits/Brawler/Abilities/BrawlerGazeAbility'],
  },
  {
    slug: 'Pillage',
    name: 'Pillage',
    armory_key: '/Armory/Helminth/Pillage',
    de_paths: ['/Lotus/Powersuits/IronFrame/Abilities/IronFrameStripAbility'],
  },
  {
    slug: 'Pull',
    name: 'Pull',
    armory_key: '/Armory/Helminth/Pull',
    de_paths: ['/Lotus/Powersuits/Mag/Abilities/PullAbility'],
  },
  {
    slug: 'Pyrotechnics',
    name: 'Pyrotechnics',
    armory_key: '/Armory/Helminth/Pyrotechnics',
    de_paths: ['/Lotus/Powersuits/Temple/Abilities/TempleShredAbility'],
  },
  {
    slug: 'Quiver',
    name: 'Quiver',
    armory_key: '/Armory/Helminth/Quiver',
    de_paths: ['/Lotus/Powersuits/Ranger/Abilities/RangerQuiverAbility'],
  },
  {
    slug: 'RadialBlind',
    name: 'Radial Blind',
    armory_key: '/Armory/Helminth/RadialBlind',
    de_paths: ['/Lotus/Powersuits/Excalibur/Abilities/RadialBlindAbility'],
  },
  {
    slug: 'Reave',
    name: 'Reave',
    armory_key: '/Armory/Helminth/Reave',
    de_paths: ['/Lotus/Powersuits/Revenant/Abilities/RevenantAfflictionAbility'],
  },
  {
    slug: 'RebuildShields',
    name: 'Rebuild Shields',
    armory_key: '/Armory/Helminth/RebuildShields',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthShieldsAbility'],
  },
  {
    slug: 'Remedium',
    name: 'Remedium',
    armory_key: '/Armory/Helminth/Remedium',
    de_paths: ['/Lotus/Powersuits/DemonFrame/Abilities/DemonFrameHealAbility'],
  },
  {
    slug: 'Resonator',
    name: 'Resonator',
    armory_key: '/Armory/Helminth/Resonator',
    de_paths: ['/Lotus/Powersuits/Bard/Abilities/BardCharmAbility'],
  },
  {
    slug: 'RestRage',
    name: 'Rest & Rage',
    armory_key: '/Armory/Helminth/RestRage',
    de_paths: ['/Lotus/Powersuits/YinYang/Abilities/YinYangTargetAbility'],
  },
  {
    slug: 'Roar',
    name: 'Roar',
    armory_key: '/Armory/Helminth/Roar',
    de_paths: ['/Lotus/Powersuits/Rhino/Abilities/RhinoRoarAbility'],
  },
  {
    slug: 'SelfPortrait',
    name: 'Self Portrait',
    armory_key: '/Armory/Helminth/SelfPortrait',
    de_paths: ['/Lotus/Powersuits/Inkblot/Abilities/InkCloneAbility'],
  },
  {
    slug: 'SentientWrath',
    name: 'Sentient Wrath',
    armory_key: '/Armory/Helminth/SentientWrath',
    de_paths: ['/Lotus/Powersuits/Sentient/Abilities/SentientStompAbility'],
  },
  {
    slug: 'Shock',
    name: 'Shock',
    armory_key: '/Armory/Helminth/Shock',
    de_paths: ['/Lotus/Powersuits/Volt/Abilities/ShockAbility'],
  },
  {
    slug: 'ShootingGallery',
    name: 'Shooting Gallery',
    armory_key: '/Armory/Helminth/ShootingGallery',
    de_paths: ['/Lotus/Powersuits/Cowgirl/Abilities/RussianRouletteAbility'],
  },
  {
    slug: 'Shuriken',
    name: 'Shuriken',
    armory_key: '/Armory/Helminth/Shuriken',
    de_paths: ['/Lotus/Powersuits/Ninja/Abilities/GlaiveAbility'],
  },
  {
    slug: 'SickeningPulse',
    name: 'Sickening Pulse',
    armory_key: '/Armory/Helminth/SickeningPulse',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthMaxStatusAbility'],
  },
  {
    slug: 'Silence',
    name: 'Silence',
    armory_key: '/Armory/Helminth/Silence',
    de_paths: ['/Lotus/Powersuits/Banshee/Abilities/SilenceAbility'],
  },
  {
    slug: 'Smite',
    name: 'Smite',
    armory_key: '/Armory/Helminth/Smite',
    de_paths: ['/Lotus/Powersuits/Paladin/Abilities/SmiteAbility'],
  },
  {
    slug: 'Spectrorage',
    name: 'Spectrorage',
    armory_key: '/Armory/Helminth/Spectrorage',
    de_paths: ['/Lotus/Powersuits/Glass/Abilities/GlassFragmentAbility'],
  },
  {
    slug: 'Spellbind',
    name: 'Spellbind',
    armory_key: '/Armory/Helminth/Spellbind',
    de_paths: ['/Lotus/Powersuits/Fairy/Abilities/FairyDustAbility'],
  },
  {
    slug: 'TempestBarrage',
    name: 'Tempest Barrage',
    armory_key: '/Armory/Helminth/TempestBarrage',
    de_paths: ['/Lotus/Powersuits/Pirate/Abilities/CannonBarrageAbility'],
  },
  {
    slug: 'Terrify',
    name: 'Terrify',
    armory_key: '/Armory/Helminth/Terrify',
    de_paths: ['/Lotus/Powersuits/Necro/Abilities/TerrorTotemAbility'],
  },
  {
    slug: 'TeslaNervos',
    name: 'Tesla Nervos',
    armory_key: '/Armory/Helminth/TeslaNervos',
    de_paths: ['/Lotus/Powersuits/Trapper/Abilities/ZapTrapAbility'],
  },
  {
    slug: 'TharrosStrike',
    name: 'Tharros Strike',
    armory_key: '/Armory/Helminth/TharrosStrike',
    de_paths: ['/Lotus/Powersuits/Hoplite/Abilities/HopliteBashAbility'],
  },
  {
    slug: 'ThermalSunder',
    name: 'Thermal Sunder',
    armory_key: '/Armory/Helminth/ThermalSunder',
    de_paths: ['/Lotus/Powersuits/Runner/Abilities/RunnerTransferAbility'],
  },
  {
    slug: 'VialRush',
    name: 'Vial Rush',
    armory_key: '/Armory/Helminth/VialRush',
    de_paths: ['/Lotus/Powersuits/Alchemist/Abilities/AlchemistVialAbility'],
  },
  {
    slug: 'VoraciousMetastasis',
    name: 'Voracious Metastasis',
    armory_key: '/Armory/Helminth/VoraciousMetastasis',
    de_paths: ['/Lotus/Powersuits/PowersuitAbilities/HelminthEnergyShareAbility'],
  },
  {
    slug: 'Warcry',
    name: 'Warcry',
    armory_key: '/Armory/Helminth/Warcry',
    de_paths: ['/Lotus/Powersuits/Berserker/Abilities/BerserkerScreamAbility'],
  },
  {
    slug: 'WebbedEmbrace',
    name: 'Webbed Embrace',
    armory_key: '/Armory/Helminth/WebbedEmbrace',
    de_paths: ['/Lotus/Powersuits/Oraxia/Abilities/OraxiaEntangleAbility'],
  },
  {
    slug: 'WellOfLife',
    name: 'Well of Life',
    armory_key: '/Armory/Helminth/WellOfLife',
    de_paths: ['/Lotus/Powersuits/Trinity/Abilities/WellOfLifeAbility'],
  },
  {
    slug: 'WrathfulAdvance',
    name: 'Wrathful Advance',
    armory_key: '/Armory/Helminth/WrathfulAdvance',
    de_paths: ['/Lotus/Powersuits/PaxDuviricus/Abilities/PaxTeleportAbility'],
  },
  {
    slug: 'WyrdScythes',
    name: 'Wyrd Scythes',
    armory_key: '/Armory/Helminth/WyrdScythes',
    de_paths: ['/Lotus/Powersuits/Dagath/Abilities/DagathVolleyAbility'],
  },
  {
    slug: 'XatasWhisper',
    name: "Xata's Whisper",
    armory_key: '/Armory/Helminth/XatasWhisper',
    de_paths: ['/Lotus/Powersuits/BrokenFrame/Abilities/BrokenRotAbility'],
  },
];
